prebuilt_cxx_library(
  name = 'catch',
  header_only = True,
  header_namespace = '',
  exported_headers = [
    'catch.hpp',
  ],
)

cxx_binary(
  name = 'apply',
  srcs = [
    'apply.cpp',
  ],
  compiler_flags = [
    '-std=c++14',
  ],
  deps = [
    '//:variant',
    ':catch',
  ],
)
